# Generated by Django 5.1.3 on 2024-11-21 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Report Date')),
                ('total_products_received', models.PositiveIntegerField(default=0, verbose_name='Total Products Received')),
                ('total_products_issued', models.PositiveIntegerField(default=0, verbose_name='Total Products Issued')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='products.category')),
                ('report_generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Report Month')),
                ('total_products_received', models.PositiveIntegerField(default=0, verbose_name='Total Products Received')),
                ('total_products_issued', models.PositiveIntegerField(default=0, verbose_name='Total Products Issued')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='products.category')),
                ('report_generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
